// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftevbsyyvkbpnmqhaprm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0ZXZic3l5dmticG5tcWhhcHJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzU3OTksImV4cCI6MjA2MjYxMTc5OX0.iQumCpPwbOAHnKi6qGhR8n1I3MLTarHbtOhs8aRcBKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);